name: Deploy Webserver

on:
  workflow_dispatch:

env:
  API_KEY: ${{ secrets.API_KEY }}
  GH_TOKEN: ${{ secrets.GIT_API_TOKEN }}
  GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}
  
  ZIP_PASSWD: ${{ secrets.ZIP_PASSWD }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PYANY_PASSWD: ${{ secrets.PYANY_PASSWD }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Installing Chrome && Extending PyAny
      run: |
        python3 -m pip install selenium webdriver_manager
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        python3 pyany_extend.py &
        
    - name: Ngrok Installation and Setup
      run: |
        curl -o ngrok-tar.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvzf ngrok-tar.tgz
        ./ngrok config add-authtoken $API_KEY

    - name: Installing Dependencies
      run: |
        python3 -m pip install streamlit streamlit_autorefresh requests

    - name: TOR Setup and Opening Serveio port forwading (59000 - 60000)
      run: |
        sudo apt-get install tor -y
        sudo systemctl start tor
        sudo python3 -m pip install tornet
        nohup sudo tornet --interval 0 --count 0 2>&1 &
        
    - name: Restore Previous State (Artifacts)
      run: |
        if gh release view 1 > /dev/null 2>&1; then
            echo "🔽 Release v1 found. Downloading..."
            gh release download 1
            unzip -P "$ZIP_PASSWD" workspace.zip
            rm -f workspace.zip
            
        else
            echo "⚠️ Release v1 does not exist. Skipping download."
        fi
        
    - name: Deleting Previous Workflow and Restoring Container
      run: |
        python3 workflow-delete.py
        python3 restore_container.py

    - name: Downloading SSHX
      run: |
        curl -sSf https://sshx.io/get | sh

    - name: Running Streamlit Server
      run: |
        python3 -m streamlit run main.py --server.headless true --server.port 5000 &

    - name: Running Ngrok Tunnel in Background
      run: |
        nohup ./ngrok http --url=yeti-glorious-redbird.ngrok-free.app 5000 > ngrok.log 2>&1 &
      
    - name: Instance keep-alive
      run: |
        SLEEP=$((RANDOM % 1800 + 18000))  # 18000–19799
        echo "Sleeping for $SLEEP seconds (~$((SLEEP / 60)) minutes)"
        sleep $SLEEP
        
    - name: Save Session State (Artifacts)
      run: |
        ZIP_OUTPUT=$(zip --password "$ZIP_PASSWD" -r workspace.zip instances 2>&1)
        ZIP_EXIT=$?

        if [ $ZIP_EXIT -ne 0 ]; then
            if echo "$ZIP_OUTPUT" | grep -q "zip error: Nothing to do!"; then
                echo "⚠️ Nothing to zip. Skipping release."
            else
                echo "❌ Unexpected zip error:"
                echo "$ZIP_OUTPUT"
                exit 1
            fi
        else
            echo "✅ Zip created successfully. Uploading to release..."
            gh release delete 1 -y || true
            gh release create 1 workspace.zip
        fi
        
    - name: Retrigger Workflow
      env:
        REPO: ${{ github.repository }}

      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GIT_API_TOKEN" \
          https://api.github.com/repos/$REPO/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
